# Generated by Django 4.1.2 on 2023-02-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='Photos/products')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modiflied_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
