# Generated by Django 4.1.2 on 2023-02-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_variation_managers'),
        ('carts', '0003_rename_carts_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='Product.variation'),
        ),
    ]
