# Generated by Django 4.1.2 on 2023-02-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Slug',
            new_name='slug',
        ),
    ]
